name: Build APK
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install EAS
        run: npm install -g eas-cli@latest
      - name: Install deps
        run: npm install
      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_GROQ_KEY: ${{ secrets.EXPO_PUBLIC_GROQ_KEY }}
          EAS_PROJECT_ID: "6a985c7d-7c88-46ea-bff6-0b59db17aac0"
